name: fts-monitoring

services:
  prometheus:
    image: prom/prometheus:v2.54.0@sha256:497fe921f22fea8535fa2bcb1c193dacc6ce98c08274257b3d18a4eaae0f9647
    volumes:
    - ./prometheus.yml:/prometheus.yml
    command:
    - --enable-feature=native-histograms
    - --config.file=/prometheus.yml
    networks: [ "fts" ]
    ports:
    - :9090

  grafana:
    image: grafana/grafana:11.1.4@sha256:886b56d5534e54f69a8cfcb4b8928da8fc753178a7a3d20c3f9b04b660169805
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
    - ./grafana/histogram.json:/etc/grafana/histogram.json
    ports:
    - 42128:3000
    networks: [ "fts" ]
networks:
  fts:
    name: ${NETWORK_NAME:-fts-smith-care}
    external: true
