name: fts-monitoring

services:
  prometheus:
    image: prom/prometheus:v2.52.0@sha256:5c435642ca4d8427ca26f4901c11114023004709037880cd7860d5b7176aa731
    volumes:
    - ./prometheus.yml:/prometheus.yml
    command:
    - --enable-feature=native-histograms
    - --config.file=/prometheus.yml
    networks: [ "fts" ]
    ports:
    - :9090

  grafana:
    image: grafana/grafana:11.1.0@sha256:079600c9517b678c10cda6006b4487d3174512fd4c6cface37df7822756ed7a5
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
    - ./grafana/histogram.json:/etc/grafana/histogram.json
    ports:
    - 42128:3000
    networks: [ "fts" ]
networks:
  fts:
    name: ${NETWORK_NAME:-fts-smith-care}
    external: true
