name: fts-monitoring

services:
  prometheus:
    image: prom/prometheus:v2.53.1@sha256:f20d3127bf2876f4a1df76246fca576b41ddf1125ed1c546fbd8b16ea55117e6
    volumes:
    - ./prometheus.yml:/prometheus.yml
    command:
    - --enable-feature=native-histograms
    - --config.file=/prometheus.yml
    networks: [ "fts" ]
    ports:
    - :9090

  grafana:
    image: grafana/grafana:11.1.3@sha256:b23b588cf7cba025ec95efba82e0d8d2e5d549a8b2cb5d50332d4175693c54e0
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
    - ./grafana/histogram.json:/etc/grafana/histogram.json
    ports:
    - 42128:3000
    networks: [ "fts" ]
networks:
  fts:
    name: ${NETWORK_NAME:-fts-smith-care}
    external: true
