name: fts-monitoring

services:
  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    volumes:
    - ./prometheus.yml:/prometheus.yml
    command:
    - --enable-feature=native-histograms
    - --config.file=/prometheus.yml
    networks: [ "monitoring", "clinical-domain", "research-domain", "trust-center" ]
    ports:
    - :9090

  grafana:
    image: grafana/grafana:11.2.2@sha256:d5133220d770aba5cb655147b619fa8770b90f41d8489a821d33b1cd34d16f89
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
    - ./grafana/dashboards:/etc/grafana/dashboards
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
    - 42128:3000
    networks: [ "monitoring" ]
networks:
  monitoring:
  clinical-domain:
    external: true
    name: fts-test_clinical-domain
  research-domain:
    external: true
    name: fts-test_research-domain
  trust-center:
    external: true
    name: fts-test_trust-center
