global:
  scrape_interval: 5s # very short interval for demo purposes

scrape_configs:
- job_name: "tca"
  metrics_path: "/actuator/prometheus"
  static_configs:
    - targets: [ "tc-agent:8080" ]

- job_name: "cda"
  metrics_path: "/actuator/prometheus"
  static_configs:
    - targets: [ "cd-agent:8080" ]

- job_name: "rda"
  metrics_path: "/actuator/prometheus"
  static_configs:
    - targets: [ "rd-agent:8080" ]


- job_name: "prometheus"
  scrape_interval: 5s
  static_configs:
    - targets: [ "localhost:9090" ]
