management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

  metrics:
    distribution.slo:
      http.server.requests: 25,100,250,500,1000,10000,60000

deIdentification:
  keystoreUrl: redis://keystore:6379
  gpas:
    fhir:
      baseUrl: http://gpas:8080/ttp-fhir/fhir/gpas
  pseudonymization:
    transportIdTTLinSeconds: 300

consent:
  gics:
    fhir:
      baseUrl: http://gics:8080/ttp-fhir/fhir/gics
