name: Analyze

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  codeql:
    env:
      MAVEN_ARGS: -B -T1C -Dmockserver.logLevel=WARN
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      security-events: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set up JDK 21
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@eb055d739abdc2e8de2e5f4ba1a8b246daa779aa # v3
      with:
        languages: java
        queries: security-and-quality

    - name: Build
      run: make compile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@eb055d739abdc2e8de2e5f4ba1a8b246daa779aa # v3
