name: Analyze

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  codeql:
    env:
      MAVEN_ARGS: -B -T1C -Dmockserver.logLevel=WARN
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      security-events: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
        queries: security-and-quality

    - name: Build
      run: make compile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
