name: Analyze

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  codeql:
    env:
      MAVEN_ARGS: -B -T1C -Dmockserver.logLevel=WARN -Dfts.retryTimeout=false
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      security-events: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set up JDK 21
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3
      with:
        languages: java
        queries: security-and-quality

    - name: Build
      run: make compile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3
