name: Build

on:
  push:
    branches: [ "*" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  MAVEN_ARGS: -B -T1C -Dmockserver.logLevel=WARN

jobs:
  analyze:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      security-events: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
        queries: security-and-quality

    - name: Build
      run: make build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  build:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        agent:
        - clinical-domain-agent
        - trust-center-agent
        - research-domain-agent
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Build Dependencies
      run: make install-dependencies

    - name: Unit Tests
      run: mvn ${MAVEN_ARGS} test --projects ${{ matrix.agent }}

    - name: Integration Tests
      run: mvn ${MAVEN_ARGS} verify --projects ${{ matrix.agent }} -DskipUnitTests

    - name: Build Agent
      run: mvn ${MAVEN_ARGS} install --projects ${{ matrix.agent }} -DskipTests

    - name: Upload Jar
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.agent }}
        path: ${{ matrix.agent }}/target/${{ matrix.agent }}.jar
        if-no-files-found: error
